name: conference_agenda_tracker
description: EventFlow - A modern conference schedule management app by thephillipsequation llc

version: 1.0.0+202510080300

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI Components
  cupertino_icons: ^1.0.2
  
  # HTTP requests
  http: ^1.1.0
  
  # File operations
  file_picker: ^6.1.1
  path_provider: ^2.1.1
  
  # Calendar parsing
  icalendar_parser: ^2.1.0
  
  # State management
  provider: ^6.1.1
  
  # Local storage
  shared_preferences: ^2.2.2
  
  # Date formatting
  intl: ^0.19.0
  
  # Material 3 theme and fonts
  google_fonts: ^6.1.0
  flutter_native_splash: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/calendars/all.ics
    - assets/calendars/demo.ics
    - assets/sample_conference.ics
    - assets/images/
    - assets/icons/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/tpe-logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/tpe-logo.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/images/tpe-logo.png"
  color_dark: "#FFFFFF"
  image_dark: "assets/images/tpe-logo.png"
  android: true
  ios: true
  web: false
