name: conference_agenda_tracker
description: A conference agenda tracker app for iOS

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI Components
  cupertino_icons: ^1.0.2
  
  # HTTP requests
  http: ^1.1.0
  
  # File operations
  file_picker: ^6.1.1
  path_provider: ^2.1.1
  
  # Calendar parsing
  icalendar_parser: ^2.1.0
  
  # State management
  provider: ^6.1.1
  
  # Local storage
  shared_preferences: ^2.2.2
  
  # Date formatting
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/calendars/all.ics
