name: iOS Build (Manual/Nightly)

on:
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: '0 2 * * *'  # Nightly at 2 AM UTC
  push:
    branches: [ main ]  # Only on main branch

jobs:
  build-ios:
    name: Build iOS
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'
        cache: true
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Build iOS (no signing)
      run: flutter build ios --no-codesign --debug
    
    - name: Upload iOS build
      uses: actions/upload-artifact@v4
      with:
        name: ios-build-nightly
        path: build/ios/
        retention-days: 7
